/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppPerfilRouteImport } from './routes/_authenticated/app.perfil'
import { Route as AuthenticatedAppHistoricoRouteImport } from './routes/_authenticated/app.historico'
import { Route as AuthenticatedAppCoachRouteImport } from './routes/_authenticated/app.coach'
import { Route as AuthenticatedAppTreinosIndexRouteImport } from './routes/_authenticated/app.treinos.index'
import { Route as AuthenticatedAppTreinosIdRouteImport } from './routes/_authenticated/app.treinos.$id'
import { Route as AuthenticatedAppSessaoIdRouteImport } from './routes/_authenticated/app.sessao.$id'
import { Route as AuthenticatedAppSessaoIdEditarRouteImport } from './routes/_authenticated/app.sessao.$id.editar'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppPerfilRoute = AuthenticatedAppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppHistoricoRoute =
  AuthenticatedAppHistoricoRouteImport.update({
    id: '/historico',
    path: '/historico',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCoachRoute = AuthenticatedAppCoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppTreinosIndexRoute =
  AuthenticatedAppTreinosIndexRouteImport.update({
    id: '/treinos/',
    path: '/treinos/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppTreinosIdRoute =
  AuthenticatedAppTreinosIdRouteImport.update({
    id: '/treinos/$id',
    path: '/treinos/$id',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSessaoIdRoute =
  AuthenticatedAppSessaoIdRouteImport.update({
    id: '/sessao/$id',
    path: '/sessao/$id',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSessaoIdEditarRoute =
  AuthenticatedAppSessaoIdEditarRouteImport.update({
    id: '/editar',
    path: '/editar',
    getParentRoute: () => AuthenticatedAppSessaoIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/app/coach': typeof AuthenticatedAppCoachRoute
  '/app/historico': typeof AuthenticatedAppHistoricoRoute
  '/app/perfil': typeof AuthenticatedAppPerfilRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/sessao/$id': typeof AuthenticatedAppSessaoIdRouteWithChildren
  '/app/treinos/$id': typeof AuthenticatedAppTreinosIdRoute
  '/app/treinos/': typeof AuthenticatedAppTreinosIndexRoute
  '/app/sessao/$id/editar': typeof AuthenticatedAppSessaoIdEditarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/coach': typeof AuthenticatedAppCoachRoute
  '/app/historico': typeof AuthenticatedAppHistoricoRoute
  '/app/perfil': typeof AuthenticatedAppPerfilRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/sessao/$id': typeof AuthenticatedAppSessaoIdRouteWithChildren
  '/app/treinos/$id': typeof AuthenticatedAppTreinosIdRoute
  '/app/treinos': typeof AuthenticatedAppTreinosIndexRoute
  '/app/sessao/$id/editar': typeof AuthenticatedAppSessaoIdEditarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/app/coach': typeof AuthenticatedAppCoachRoute
  '/_authenticated/app/historico': typeof AuthenticatedAppHistoricoRoute
  '/_authenticated/app/perfil': typeof AuthenticatedAppPerfilRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/sessao/$id': typeof AuthenticatedAppSessaoIdRouteWithChildren
  '/_authenticated/app/treinos/$id': typeof AuthenticatedAppTreinosIdRoute
  '/_authenticated/app/treinos/': typeof AuthenticatedAppTreinosIndexRoute
  '/_authenticated/app/sessao/$id/editar': typeof AuthenticatedAppSessaoIdEditarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/app'
    | '/app/coach'
    | '/app/historico'
    | '/app/perfil'
    | '/app/'
    | '/app/sessao/$id'
    | '/app/treinos/$id'
    | '/app/treinos/'
    | '/app/sessao/$id/editar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app/coach'
    | '/app/historico'
    | '/app/perfil'
    | '/app'
    | '/app/sessao/$id'
    | '/app/treinos/$id'
    | '/app/treinos'
    | '/app/sessao/$id/editar'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/app'
    | '/_authenticated/app/coach'
    | '/_authenticated/app/historico'
    | '/_authenticated/app/perfil'
    | '/_authenticated/app/'
    | '/_authenticated/app/sessao/$id'
    | '/_authenticated/app/treinos/$id'
    | '/_authenticated/app/treinos/'
    | '/_authenticated/app/sessao/$id/editar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/perfil': {
      id: '/_authenticated/app/perfil'
      path: '/perfil'
      fullPath: '/app/perfil'
      preLoaderRoute: typeof AuthenticatedAppPerfilRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/historico': {
      id: '/_authenticated/app/historico'
      path: '/historico'
      fullPath: '/app/historico'
      preLoaderRoute: typeof AuthenticatedAppHistoricoRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/coach': {
      id: '/_authenticated/app/coach'
      path: '/coach'
      fullPath: '/app/coach'
      preLoaderRoute: typeof AuthenticatedAppCoachRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/treinos/': {
      id: '/_authenticated/app/treinos/'
      path: '/treinos'
      fullPath: '/app/treinos/'
      preLoaderRoute: typeof AuthenticatedAppTreinosIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/treinos/$id': {
      id: '/_authenticated/app/treinos/$id'
      path: '/treinos/$id'
      fullPath: '/app/treinos/$id'
      preLoaderRoute: typeof AuthenticatedAppTreinosIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/sessao/$id': {
      id: '/_authenticated/app/sessao/$id'
      path: '/sessao/$id'
      fullPath: '/app/sessao/$id'
      preLoaderRoute: typeof AuthenticatedAppSessaoIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/sessao/$id/editar': {
      id: '/_authenticated/app/sessao/$id/editar'
      path: '/editar'
      fullPath: '/app/sessao/$id/editar'
      preLoaderRoute: typeof AuthenticatedAppSessaoIdEditarRouteImport
      parentRoute: typeof AuthenticatedAppSessaoIdRoute
    }
  }
}

interface AuthenticatedAppSessaoIdRouteChildren {
  AuthenticatedAppSessaoIdEditarRoute: typeof AuthenticatedAppSessaoIdEditarRoute
}

const AuthenticatedAppSessaoIdRouteChildren: AuthenticatedAppSessaoIdRouteChildren =
  {
    AuthenticatedAppSessaoIdEditarRoute: AuthenticatedAppSessaoIdEditarRoute,
  }

const AuthenticatedAppSessaoIdRouteWithChildren =
  AuthenticatedAppSessaoIdRoute._addFileChildren(
    AuthenticatedAppSessaoIdRouteChildren,
  )

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppCoachRoute: typeof AuthenticatedAppCoachRoute
  AuthenticatedAppHistoricoRoute: typeof AuthenticatedAppHistoricoRoute
  AuthenticatedAppPerfilRoute: typeof AuthenticatedAppPerfilRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppSessaoIdRoute: typeof AuthenticatedAppSessaoIdRouteWithChildren
  AuthenticatedAppTreinosIdRoute: typeof AuthenticatedAppTreinosIdRoute
  AuthenticatedAppTreinosIndexRoute: typeof AuthenticatedAppTreinosIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppCoachRoute: AuthenticatedAppCoachRoute,
  AuthenticatedAppHistoricoRoute: AuthenticatedAppHistoricoRoute,
  AuthenticatedAppPerfilRoute: AuthenticatedAppPerfilRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppSessaoIdRoute: AuthenticatedAppSessaoIdRouteWithChildren,
  AuthenticatedAppTreinosIdRoute: AuthenticatedAppTreinosIdRoute,
  AuthenticatedAppTreinosIndexRoute: AuthenticatedAppTreinosIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
