/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppPerfilRouteImport } from './routes/_authenticated/app.perfil'
import { Route as AuthenticatedAppMensagensRouteImport } from './routes/_authenticated/app.mensagens'
import { Route as AuthenticatedAppMcpTesteRouteImport } from './routes/_authenticated/app.mcp-teste'
import { Route as AuthenticatedAppHistoricoRouteImport } from './routes/_authenticated/app.historico'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as AuthenticatedAppTreinosIndexRouteImport } from './routes/_authenticated/app.treinos.index'
import { Route as AuthenticatedAppAlunosIndexRouteImport } from './routes/_authenticated/app.alunos.index'
import { Route as AuthenticatedAppTreinosIdRouteImport } from './routes/_authenticated/app.treinos.$id'
import { Route as AuthenticatedAppSessaoIdRouteImport } from './routes/_authenticated/app.sessao.$id'
import { Route as AuthenticatedAppAlunosIdRouteImport } from './routes/_authenticated/app.alunos.$id'
import { Route as AuthenticatedAppSessaoIdEditarRouteImport } from './routes/_authenticated/app.sessao.$id.editar'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppPerfilRoute = AuthenticatedAppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppMensagensRoute =
  AuthenticatedAppMensagensRouteImport.update({
    id: '/mensagens',
    path: '/mensagens',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppMcpTesteRoute =
  AuthenticatedAppMcpTesteRouteImport.update({
    id: '/mcp-teste',
    path: '/mcp-teste',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppHistoricoRoute =
  AuthenticatedAppHistoricoRouteImport.update({
    id: '/historico',
    path: '/historico',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppTreinosIndexRoute =
  AuthenticatedAppTreinosIndexRouteImport.update({
    id: '/treinos/',
    path: '/treinos/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAlunosIndexRoute =
  AuthenticatedAppAlunosIndexRouteImport.update({
    id: '/alunos/',
    path: '/alunos/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppTreinosIdRoute =
  AuthenticatedAppTreinosIdRouteImport.update({
    id: '/treinos/$id',
    path: '/treinos/$id',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSessaoIdRoute =
  AuthenticatedAppSessaoIdRouteImport.update({
    id: '/sessao/$id',
    path: '/sessao/$id',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAlunosIdRoute =
  AuthenticatedAppAlunosIdRouteImport.update({
    id: '/alunos/$id',
    path: '/alunos/$id',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSessaoIdEditarRoute =
  AuthenticatedAppSessaoIdEditarRouteImport.update({
    id: '/editar',
    path: '/editar',
    getParentRoute: () => AuthenticatedAppSessaoIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/app/historico': typeof AuthenticatedAppHistoricoRoute
  '/app/mcp-teste': typeof AuthenticatedAppMcpTesteRoute
  '/app/mensagens': typeof AuthenticatedAppMensagensRoute
  '/app/perfil': typeof AuthenticatedAppPerfilRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/alunos/$id': typeof AuthenticatedAppAlunosIdRoute
  '/app/sessao/$id': typeof AuthenticatedAppSessaoIdRouteWithChildren
  '/app/treinos/$id': typeof AuthenticatedAppTreinosIdRoute
  '/app/alunos/': typeof AuthenticatedAppAlunosIndexRoute
  '/app/treinos/': typeof AuthenticatedAppTreinosIndexRoute
  '/app/sessao/$id/editar': typeof AuthenticatedAppSessaoIdEditarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/app/historico': typeof AuthenticatedAppHistoricoRoute
  '/app/mcp-teste': typeof AuthenticatedAppMcpTesteRoute
  '/app/mensagens': typeof AuthenticatedAppMensagensRoute
  '/app/perfil': typeof AuthenticatedAppPerfilRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/alunos/$id': typeof AuthenticatedAppAlunosIdRoute
  '/app/sessao/$id': typeof AuthenticatedAppSessaoIdRouteWithChildren
  '/app/treinos/$id': typeof AuthenticatedAppTreinosIdRoute
  '/app/alunos': typeof AuthenticatedAppAlunosIndexRoute
  '/app/treinos': typeof AuthenticatedAppTreinosIndexRoute
  '/app/sessao/$id/editar': typeof AuthenticatedAppSessaoIdEditarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/app/historico': typeof AuthenticatedAppHistoricoRoute
  '/_authenticated/app/mcp-teste': typeof AuthenticatedAppMcpTesteRoute
  '/_authenticated/app/mensagens': typeof AuthenticatedAppMensagensRoute
  '/_authenticated/app/perfil': typeof AuthenticatedAppPerfilRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/alunos/$id': typeof AuthenticatedAppAlunosIdRoute
  '/_authenticated/app/sessao/$id': typeof AuthenticatedAppSessaoIdRouteWithChildren
  '/_authenticated/app/treinos/$id': typeof AuthenticatedAppTreinosIdRoute
  '/_authenticated/app/alunos/': typeof AuthenticatedAppAlunosIndexRoute
  '/_authenticated/app/treinos/': typeof AuthenticatedAppTreinosIndexRoute
  '/_authenticated/app/sessao/$id/editar': typeof AuthenticatedAppSessaoIdEditarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/mcp'
    | '/privacidade'
    | '/termos'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/app'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/app/historico'
    | '/app/mcp-teste'
    | '/app/mensagens'
    | '/app/perfil'
    | '/app/'
    | '/app/alunos/$id'
    | '/app/sessao/$id'
    | '/app/treinos/$id'
    | '/app/alunos/'
    | '/app/treinos/'
    | '/app/sessao/$id/editar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/mcp'
    | '/privacidade'
    | '/termos'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/app/historico'
    | '/app/mcp-teste'
    | '/app/mensagens'
    | '/app/perfil'
    | '/app'
    | '/app/alunos/$id'
    | '/app/sessao/$id'
    | '/app/treinos/$id'
    | '/app/alunos'
    | '/app/treinos'
    | '/app/sessao/$id/editar'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/mcp'
    | '/privacidade'
    | '/termos'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/app'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/app/historico'
    | '/_authenticated/app/mcp-teste'
    | '/_authenticated/app/mensagens'
    | '/_authenticated/app/perfil'
    | '/_authenticated/app/'
    | '/_authenticated/app/alunos/$id'
    | '/_authenticated/app/sessao/$id'
    | '/_authenticated/app/treinos/$id'
    | '/_authenticated/app/alunos/'
    | '/_authenticated/app/treinos/'
    | '/_authenticated/app/sessao/$id/editar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  McpRoute: typeof McpRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  TermosRoute: typeof TermosRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/perfil': {
      id: '/_authenticated/app/perfil'
      path: '/perfil'
      fullPath: '/app/perfil'
      preLoaderRoute: typeof AuthenticatedAppPerfilRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/mensagens': {
      id: '/_authenticated/app/mensagens'
      path: '/mensagens'
      fullPath: '/app/mensagens'
      preLoaderRoute: typeof AuthenticatedAppMensagensRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/mcp-teste': {
      id: '/_authenticated/app/mcp-teste'
      path: '/mcp-teste'
      fullPath: '/app/mcp-teste'
      preLoaderRoute: typeof AuthenticatedAppMcpTesteRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/historico': {
      id: '/_authenticated/app/historico'
      path: '/historico'
      fullPath: '/app/historico'
      preLoaderRoute: typeof AuthenticatedAppHistoricoRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/treinos/': {
      id: '/_authenticated/app/treinos/'
      path: '/treinos'
      fullPath: '/app/treinos/'
      preLoaderRoute: typeof AuthenticatedAppTreinosIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/alunos/': {
      id: '/_authenticated/app/alunos/'
      path: '/alunos'
      fullPath: '/app/alunos/'
      preLoaderRoute: typeof AuthenticatedAppAlunosIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/treinos/$id': {
      id: '/_authenticated/app/treinos/$id'
      path: '/treinos/$id'
      fullPath: '/app/treinos/$id'
      preLoaderRoute: typeof AuthenticatedAppTreinosIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/sessao/$id': {
      id: '/_authenticated/app/sessao/$id'
      path: '/sessao/$id'
      fullPath: '/app/sessao/$id'
      preLoaderRoute: typeof AuthenticatedAppSessaoIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/alunos/$id': {
      id: '/_authenticated/app/alunos/$id'
      path: '/alunos/$id'
      fullPath: '/app/alunos/$id'
      preLoaderRoute: typeof AuthenticatedAppAlunosIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/sessao/$id/editar': {
      id: '/_authenticated/app/sessao/$id/editar'
      path: '/editar'
      fullPath: '/app/sessao/$id/editar'
      preLoaderRoute: typeof AuthenticatedAppSessaoIdEditarRouteImport
      parentRoute: typeof AuthenticatedAppSessaoIdRoute
    }
  }
}

interface AuthenticatedAppSessaoIdRouteChildren {
  AuthenticatedAppSessaoIdEditarRoute: typeof AuthenticatedAppSessaoIdEditarRoute
}

const AuthenticatedAppSessaoIdRouteChildren: AuthenticatedAppSessaoIdRouteChildren =
  {
    AuthenticatedAppSessaoIdEditarRoute: AuthenticatedAppSessaoIdEditarRoute,
  }

const AuthenticatedAppSessaoIdRouteWithChildren =
  AuthenticatedAppSessaoIdRoute._addFileChildren(
    AuthenticatedAppSessaoIdRouteChildren,
  )

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppHistoricoRoute: typeof AuthenticatedAppHistoricoRoute
  AuthenticatedAppMcpTesteRoute: typeof AuthenticatedAppMcpTesteRoute
  AuthenticatedAppMensagensRoute: typeof AuthenticatedAppMensagensRoute
  AuthenticatedAppPerfilRoute: typeof AuthenticatedAppPerfilRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppAlunosIdRoute: typeof AuthenticatedAppAlunosIdRoute
  AuthenticatedAppSessaoIdRoute: typeof AuthenticatedAppSessaoIdRouteWithChildren
  AuthenticatedAppTreinosIdRoute: typeof AuthenticatedAppTreinosIdRoute
  AuthenticatedAppAlunosIndexRoute: typeof AuthenticatedAppAlunosIndexRoute
  AuthenticatedAppTreinosIndexRoute: typeof AuthenticatedAppTreinosIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppHistoricoRoute: AuthenticatedAppHistoricoRoute,
  AuthenticatedAppMcpTesteRoute: AuthenticatedAppMcpTesteRoute,
  AuthenticatedAppMensagensRoute: AuthenticatedAppMensagensRoute,
  AuthenticatedAppPerfilRoute: AuthenticatedAppPerfilRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppAlunosIdRoute: AuthenticatedAppAlunosIdRoute,
  AuthenticatedAppSessaoIdRoute: AuthenticatedAppSessaoIdRouteWithChildren,
  AuthenticatedAppTreinosIdRoute: AuthenticatedAppTreinosIdRoute,
  AuthenticatedAppAlunosIndexRoute: AuthenticatedAppAlunosIndexRoute,
  AuthenticatedAppTreinosIndexRoute: AuthenticatedAppTreinosIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  McpRoute: McpRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  TermosRoute: TermosRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
